//! Standard token interface trait for the Stellar Wrap Registry.
//!
//! Extracts standard token interface methods (`name`, `symbol`, `decimals`,
//! `balance_of`) into a dedicated trait, reducing boilerplate in `lib.rs` and
//! promoting interface reuse across Soroban client tooling.
//!
//! **Note on SEP-41 Compatibility:**
//! This contract represents a **soulbound wrap registry** rather than a conventional
//! fungible token. Methods exposed by this interface exist for compatibility, but
//! callers must not treat the contract as a tradable token balance provider.
//!
//! The trait is implemented directly in `lib.rs` with `#[contractimpl]` so
//! the Soroban macro generates client types in the correct crate scope.
//!
//! # Standard Interface Methods
//!
//! | Method       | Description                         |
//! |--------------|-------------------------------------|
//! | `name`       | Registry display name (default: "Stellar Wrap Registry") |
//! | `symbol`     | Registry ticker symbol (default: "WRAP") |
//! | `decimals`   | Number of decimals (always 0; wrap records are indivisible) |
//! | `balance_of` | Count of active wrap records for a user (not a token balance) |
//!
//! # Reentrancy Analysis (Issue #886)
//!
//! This module defines the token interface surface. The concrete token client
//! used for cross-contract calls is generated by `#[contractimpl]` in `lib.rs`
//! and is invoked from the stake module (`stake`, `unstake`, `withdraw_stake`).
//! Those call sites are the classic reentrancy path: a hostile token contract
//! can re-enter the registry from inside a transfer callback.
//!
//! The invariant enforced at every such call site is **checks-effects-interactions**:
//! all registry state (stake records, balances, totals) is written *before* the
//! external token call, so a re-entrant invocation observes a fully consistent
//! state and cannot double-spend or double-count. The hostile-mock tests in
//! `src/test_vectors.rs` exercise this by re-entering on callback.
//!
//! ## External call sites transferring control
//!
//! | Call site        | External call            | State written before call |
//! |------------------|--------------------------|---------------------------|
//! | `stake`          | token `transfer` (in)    | stake record + totals     |
//! | `unstake`        | token `transfer` (out)   | stake record + totals     |
//! | `withdraw_stake` | token `transfer` (out)   | stake record + totals     |
//! | oracle client    | oracle `get_price`       | none (read-only, no state)|
//!
//! No invariant is observable in a broken intermediate state: the token transfer
//! is the final step of each mutating entry point, and any re-entrant call sees
//! the post-effect state.

use soroban_sdk::{Address, Env, String};

/// Standard token interface trait for `StellarWrapContract`.
///
/// Implemented in `lib.rs` via `#[contractimpl]` so these methods are
/// automatically exposed as contract functions. The implementations
/// delegate to the `queries` module for storage access.
///
/// This trait exposes token-shaped metadata and lookup functions for a soulbound wrap
/// registry, implementing a deliberate subset of standard token methods.
pub trait TokenInterface {
    /// Returns the registry display name, either the admin-set override or the default.
    fn name(e: Env) -> String;

    /// Returns the registry ticker symbol, either the admin-set override or the default.
    fn symbol(e: Env) -> String;

    /// Returns the number of decimals (`0`).
    ///
    /// `decimals()` intentionally returns `0` because the contract represents discrete,
    /// indivisible wrap records rather than divisible fungible token amounts. There are no
    /// fractional wrap-record units.
    fn decimals(e: Env) -> u32;

    /// Returns the count of active wrap records associated with the given user address.
    ///
    /// **Registry Semantics:**
    /// - The returned value is a **count of wrap records**, NOT a fungible token balance.
    /// - The result must NOT be interpreted as a tradable or spendable token amount.
    /// - The `i128` return type is used for token interface compatibility; under the hood,
    ///   it is a widened `u32` wrap record counter (`WrapCount`) stored in persistent storage.
    fn balance_of(e: Env, user: Address) -> i128;
}
